## Import NumPy Library

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5], dtype='int16')
print(arr)

[1 2 3 4 5]


In [3]:
arr2 = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]]) # two dimensional array of list
print(arr2)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
arr2.ndim

2

In [7]:
# Get shape
arr2.shape # 2 rows and 3 columns (2,3)

(2, 3)

In [9]:
# Get Type - how much it is taking memory
arr2.dtype

dtype('float64')

In [10]:
# Get size
arr2.itemsize

8

In [14]:
# Get total size
arr2.nbytes # arr2.size || arr2.size * arr2.itemsize

48