### Accessing/Changing specific elements, rows, columns, etc

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
# Get shape
a.shape

(2, 7)

In [8]:
# Get a specific element [r,c]
a[1, 5] # you can use negative int a[1,-2] points to second last column in second row

np.int64(13)

In [9]:
# Get specific row
a[0, :] # no column only first row

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
# Get specific column
a[:, 0]

array([1, 8])

In [12]:
# Change specific element
a[1,-2] = 100
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 100  14]]


In [13]:
# Change complete column
a[:, 2] = [20,30]
print(a)

[[  1   2  20   4   5   6   7]
 [  8   9  30  11  12 100  14]]


In [14]:
# Change complete row
a[0, :] = [10, 20, 30, 40, 50, 60, 70]
print(a)

[[ 10  20  30  40  50  60  70]
 [  8   9  30  11  12 100  14]]
